version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Create and activate Python virtual environment, install dependencies, and run tests
      - run:
          name: Install dependencies and run tests
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest

      # Generate Allure report using Allure CLI
      - run:
          when: always
          name: Generate Allure report
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk npm
            sudo npm install -g allure-commandline --save-dev
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
            java -version
            npm --version
            allure --version
            allure generate --clean -o logs/allure-report

      # Store Allure report as CircleCI artifact
      - store_artifacts:
          path: logs/allure-report

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
