version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9 # Start with the official Python 3.9 image

    steps:
      - checkout # Checkout the code from the repo

      # Install OpenJDK 8 and npm (and other dependencies)
      - run:
          name: Install Java 8, npm, and Allure CLI
          command: |
            # Update package list and install dependencies
            sudo apt-get update
            sudo apt-get install -y openjdk-8-jdk npm

            # Install Allure CLI using npm
            sudo npm install -g allure-commandline --save-dev

            # Set JAVA_HOME environment variable
            echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV

            # Verify installations
            java -version
            npm --version
            allure --version

      # Create and activate Python virtual environment
      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv  # Create the virtual environment
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install all dependencies

      # Run pytest tests and store results in allure-results directory
      - run:
          name: Run pytest tests
          when: always
          command: |
            source venv/bin/activate  # Activate virtual environment
            pytest --alluredir=allure-results  # Run tests and save results

      # Generate Allure report
      - run:
          name: Generate Allure report using Allure CLI
          when: always
          command: |
            allure generate allure-results --clean -o allure-report  # Generate Allure report

      # Configure Git for Deployment to main branch (optional, if needed)
      - run:
          name: Configure Git for Deployment to main branch
          command: |
            git config --global user.name "preetm-AO"
            git config --global user.email "preet.mehta@contractors.appomni.com"

      # Clone the main branch and deploy the generated Allure report (optional)
      - run:
          name: Clone main branch and deploy Allure report
          command: |
            git clone --single-branch --branch main https://github.com/manavptl-star/appomni-allure-report.git
            cd appomni-allure-report
            rm -rf *
            cp -r ../allure-report/* .
            git commit -m "Update Allure report"
            git push origin main

      # Store generated Allure report as CircleCI artifact
      - store_artifacts:
          path: allure-report # Store the generated Allure report as an artifact

workflows:
  version: 2
  build:
    jobs:
      - build
