version: 2.1

### PARAMETERS
parameters:
  run_build:
    default: true
    type: boolean

### JOBS
jobs:
  build:
    docker:
      - image: circleci/python:3.9 # Official CircleCI Python image

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            echo "$PWD"
            python --version
            ls -a
            pip install -r requirements.txt
      - run:
          name: Install Java (required for Allure CLI)
          command: |
            # Install OpenJDK (Java 11 or higher) to avoid the JAVA_HOME error
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk

            # Set JAVA_HOME environment variable
            echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV

            # Verify Java installation
            java -version
      - run:
          name: Download Allure CLI
          command: |
            # Download Allure Command Line Tool from GitHub releases page
            ALLURE_VERSION="2.18.1"  # Specify the desired version here
            wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz

            # Extract the downloaded tar.gz file
            tar -zxvf allure-$ALLURE_VERSION.tgz

            # Move the 'allure' executable to /usr/local/bin (optional)
            sudo mv allure-$ALLURE_VERSION/bin/allure /usr/local/bin/allure

            # Verify allure installation
            allure --version
      - run:
          name: Run pytest tests
          when: always
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Run Allure report generation
          when: always
          command: |
            allure --version
            allure generate allure-results --clean -o allure-report

      - run:
          name: Configure Git for Deployment to main branch
          command: |
            git config --global user.name "preetm-AO"
            git config --global user.email "preet.mehta@contractors.appomni.com"

      - run:
          name: Clone main branch and deploy Allure report
          command: |
            git clone --single-branch --branch main https://github.com/manavptl-star/appomni-allure-report.git  
            cd appomni-allure-report
            rm -rf *  
            cp -r ../allure-report/* .  
            git commit -m "Update Allure report"
            git push origin main

      - store_artifacts:
          path: allure-report # Store the generated Allure report as an artifact in CircleCI

### WORKFLOWS
workflows:
  version: 2
  build:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build:
          filters:
            branches:
              only: main # Ensure this only runs on the main branch
