version: 2.1

### PARAMETERS
parameters:
  run_build:
    default: true
    type: boolean

### JOBS
jobs:
  build:
    docker:
      - image: circleci/python:3.9 # Official CircleCI Python image

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            echo "$PWD"
            python --version
            ls -a
            pip install -r requirements.txt
      - run:
          name: Install Node.js and Allure command-line tool
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
            npm install -g allure-commandline --save-dev
      - run:
          name: Run pytest tests
          when: always
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Run Allure report generation
          when: always
          command: |
            allure generate allure-results --clean -o allure-report

      - run:
          name: Configure Git for Deployment to main branch
          command: |
            git config --global user.name "preetm-AO"
            git config --global user.email "preet.mehta@contractors.appomni.com"

      - run:
          name: Clone main branch and deploy Allure report
          command: |
            git clone --single-branch --branch main https://github.com/manavptl-star/appomni-allure-report.git  
            cd appomni-allure-report
            rm -rf *  
            cp -r ../allure-report/* .  
            git commit -m "Update Allure report"
            git push origin main

      - store_artifacts:
          path: allure-report # Store the generated Allure report as an artifact in CircleCI

### WORKFLOWS
workflows:
  version: 2
  build:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build:
          filters:
            branches:
              only: main # Ensure this only runs on the main branch
